<header class="Header" role="banner">
  <a class="Header-link is-current" href="#relative#home/index.html">
    Jaclyn Drum Interior Design
  </a>
  <nav class="Header-nav">
    <ol class="Header-navList">
      <li><a class="Header-link #HOME_PAGE#" href="#relative#home/index.html">Home</a></li>
      <li><a class="Header-link #ABOUT_PAGE#" href="#relative#about/index.html">About</a></li>
      <li><a class="Header-link #PORTFOLIO_PAGE#" href="#relative#portfolio/index.html">Portfolio</a></li>
      <li><a class="Header-link #SERVICES_PAGE#" href="#relative#services/index.html">Design services</a></li>
      <li><a class="Header-link #CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
    </ol>
  </nav>
  <details class="Header-details">
    <summary class="Header-summary">Menu</summary>
    <nav class="Header-mobileNav">
      <ol class="Header-mobileNavList">
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #HOME_PAGE#" href="#relative#home/index.html">Home</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #ABOUT_PAGE#" href="#relative#about/index.html">About</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #PORTFOLIO_PAGE#" href="#relative#portfolio/index.html">Portfolio</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #SERVICES_PAGE#" href="#relative#services/index.html">Design services</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
      </ol>
    </nav>
  </details>
</header>
