<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-5607338-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-5607338-2');
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>#PAGE_TITLE# | Jaclyn Drum Interior Design</title>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,600%7CStalemate&amp;display=swap" rel="stylesheet">
  <link href="#relative#css/suitcss.css" rel="stylesheet">
  <link href="#relative#css/style.css" rel="stylesheet">
</head>
