<header class="Header" role="banner">
  <a class="Header-link is-current" href="#relative#">
    Jaclyn Drum Interior Design
  </a>
  <nav class="Header-nav">
    <ol class="Header-navList">
      <li><a class="Header-link #HOME_PAGE#" href="#relative#">Home</a></li>
      <li><a class="Header-link #ABOUT_PAGE#" href="#relative#about/">About</a></li>
      <li><a class="Header-link #PORTFOLIO_PAGE#" href="#relative#portfolio/">Portfolio</a></li>
      <li><a class="Header-link #SERVICES_PAGE#" href="#relative#services/">Design services</a></li>
      <li><a class="Header-link #CONTACT_PAGE#" href="#relative#contact/">Contact</a></li>
    </ol>
  </nav>
  <details class="Header-details">
    <summary class="Header-summary">Menu</summary>
    <nav class="Header-mobileNav">
      <ol class="Header-mobileNavList">
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #HOME_PAGE#" href="#relative#">Home</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #ABOUT_PAGE#" href="#relative#about/">About</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #PORTFOLIO_PAGE#" href="#relative#portfolio/">Portfolio</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #SERVICES_PAGE#" href="#relative#services/">Design services</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #CONTACT_PAGE#" href="#relative#contact/">Contact</a></li>
      </ol>
    </nav>
  </details>
</header>
