<header role="banner">
  <a href="#relative#home/index.html">
    Jaclyn Drum Interior Design
  </a>
  <nav>
    <ol>
      <li><a class="#HOME_PAGE#" href="#relative#home/index.html">Home</a></li>
      <li><a class="#ABOUT_PAGE#" href="#relative#about/index.html">About</a></li>
      <li><a class="#PORTFOLIO_PAGE#" href="#relative#portfolio/index.html">Portfolio</a></li>
      <li><a class="#SERVICES_PAGE#" href="#relative#services/index.html">Design services</a></li>
      <li><a class="#CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
    </ol>
  </nav>
  <details>
    <summary>Menu</summary>
    <nav>
      <ol>
        <li><a class="#HOME_PAGE#" href="#relative#home/index.html">Home</a></li>
        <li><a class="#ABOUT_PAGE#" href="#relative#about/index.html">About</a></li>
        <li><a class="#PORTFOLIO_PAGE#" href="#relative#portfolio/index.html">Portfolio</a></li>
        <li><a class="#SERVICES_PAGE#" href="#relative#services/index.html">Design services</a></li>
        <li><a class="#CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
      </ol>
    </nav>
  </details>
</header>
