<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>#PAGE_TITLE# | Jaclyn Drum Interior Design</title>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,600%7CStalemate&amp;display=swap" rel="stylesheet">
  <link href="#relative#css/suitcss.css" rel="stylesheet">
  <link href="#relative#css/style.css" rel="stylesheet">
</head>
